<?php
$title = 'Produtos';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>modelo</th>
        <th>preço</th>
        <th>cor</th>
        <th>descrição</th>
        <th>custo de transporte
        </th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $products) : // <-- change here! ?>
        <tr>
            <td><?= $this->escapeHtml($products->model) ?></td>
            <td><?= $this->escapeHtml($products->price) ?></td>
            <td><?= $this->escapeHtml($products->color) ?></td>
            <td><?= $this->escapeHtml($products->description) ?></td>
            <td>
                <a href="<?= $this->url('products', ['action' => 'calcular_frete', 'id' => $products->id]) ?>">Calcular frete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?= $this->paginationControl(
// The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'products']
); ?>
