<?php
$title = 'Gerenciar Custo';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Nome');

$city = $form->get('city');
$city->setAttribute('class', 'form-control');
$city->setAttribute('placeholder', 'Cidade');

$freightAir = $form->get('freight_air');
$freightAir->setAttribute('class', 'form-control');
$freightAir->setAttribute('placeholder', 'Frete aerea');

$freightWater = $form->get('freight_water');
$freightWater->setAttribute('class', 'form-control');
$freightWater->setAttribute('placeholder', 'Frete aquatico');

$freightEarthly = $form->get('freight_earthly');
$freightEarthly->setAttribute('class', 'form-control');
$freightEarthly->setAttribute('placeholder', 'Frete terreste');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url(null, [
    'action' => 'gerenciar_custos',
    'id'     => $id,
]));

$form->prepare();

echo $this->form()->openTag($form);
?>

    <div class="form-group">
        <?= $this->formLabel($name) ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($city) ?>
        <?= $this->formElement($city) ?>
        <?= $this->formElementErrors()->render($city, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($freightAir) ?>
        <?= $this->formElement($freightAir) ?>
        <?= $this->formElementErrors()->render($freightAir, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($freightWater) ?>
        <?= $this->formElement($freightWater) ?>
        <?= $this->formElementErrors()->render($freightWater, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($freightEarthly) ?>
        <?= $this->formElement($freightEarthly) ?>
        <?= $this->formElementErrors()->render($freightEarthly, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
