<?php
$title = 'Gerenciamento de Transporte';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1>Gerenciamento de <span class="zf-green">Transporte</span></h1>

    <p>
        Prova 
        <a href="http://triadsystems.com.br/itriad/" target="_blank">ZF 
        iTriad
        </a>.
        
    </p>

</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                Transportadoras
                </h3>
            </div>
            <div class="panel-body">
                <p>
                    Companias de transporte e logistica
                </p>

                <p>
                    <a class="btn btn-success pull-right" href="<?php echo($this-> basePath("transportadoras")); ?>">
                    Transportadoras &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Custos de Frete</h3>
            </div>
            <div class="panel-body">
                <p>
                    Aqui voce gerencia os custos de frete 
                </p>
                <p>
                    <a class="btn btn-success pull-right" href="<?php echo($this-> basePath("custos")); ?>">
                        Gerenciar custos &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>



    <!-- <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                Transportadoras
                </h3>
            </div>
            <div class="panel-body">
                <p>
                    Companias de transporte e logistica
                </p>

                <p>
                    <a class="btn btn-success pull-right" href="<?php echo($this-> basePath("custos")); ?>">
                    Transportadoras &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div> -->
</div>
